#!/bin/bash
    declare -i count
    read line
    words=($line)
    if [ ${words[0]} == 'cs' ] || [ ${words[0]} == 'cvmfs' ] || [ ${words[0]} == 'client' || [ ${words[0]} == 'iclient' ]; then
        if [ ${words[1]} == 'boot' ] || [ ${words[1]} == 'clock' ]; then
            counter='nep52-'${words[0]}'-'${words[1]}
            count=`redis-cli get $counter`
            count=($count+1)
            redis-cli set $counter $count
            comment='- counted.'
        else comment='- bad second parameter.'
        fi
    else comment='- bad first parameter.'
    fi
    logger -t $0 $line $comment
